version: '2'
services:
    couchbase:
        build: .
        image: vice-db
        environment:
         - CLUSTER=localhost:8091
         - USER=admin
         - PASS=secret
         - PORT=8091
         - RAMSIZEMB=2048
         - RAMSIZEINDEXMB=512
         - RAMSIZEFTSMB=512
         - BUCKETS=vice-users vice-environments vice-images vice-deployments
         - BUCKETSIZES=512 512 512 512
